### ISSUE TITLE
Computer name contains dash which is not allowed in node names

### ISSUE THREAD

**Issue by Spir0u** [fkie/fkie-multi-agent-suite#3]
And therefore the mas-deamon cannot be started:
```
ros2 run fkie_mas_daemon mas-daemon 
Traceback (most recent call last):
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 175, in __init__
    self.__node = _rclpy.Node(
ValueError: invalid node name: node name must not contain characters other than alphanumerics or '_', at ./src/rcl/node.c:163

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spir0u/atn_ws/install/fkie_mas_daemon/lib/fkie_mas_daemon/mas-daemon", line 33, in <module>
    sys.exit(load_entry_point('fkie-mas-daemon', 'console_scripts', 'mas-daemon')())
  File "/home/spir0u/atn_ws/build/fkie_mas_daemon/fkie_mas_daemon/__init__.py", line 28, in main
    launcher = RosNodeLauncher()
  File "/home/spir0u/atn_ws/build/fkie_mas_daemon/fkie_mas_daemon/ros_node.py", line 53, in __init__
    self.ros_node = rclpy.create_node(self.name, namespace=NM_NAMESPACE)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 172, in create_node
    return Node(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 185, in __init__
    validate_node_name(node_name)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/validate_node_name.py", line 34, in validate_node_name
    raise InvalidNodeNameException(node_name, error_msg, invalid_index)
rclpy.exceptions.InvalidNodeNameException: Invalid node name: node name must not contain characters other than alphanumerics or '_':
  '_daemon_spir0u-Notebook'
                 ^
[ros2run]: Process exited with failure 1

```

**Comment by atiderko** [comment]
thank you for reporting!

It should be fixed now.
